import Head from 'next/head';

export default function Home() {
  return (
    <div className='min-w-full min-h-screen text-center text-black '>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <p className='text-6xl font-normal text-red-700 font-roboto'>OY</p>
        <h2 className='text-6xl font-normal text-red-700 font-josefin-sans'>OY</h2>
        FFFF
      </main>
    </div>
  );
}
