import Head from 'next/head';

export default function Home() {
  return (
    <div className='bg-[#333] min-h-screen min-w-full text-white text-center'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        FFFF
      </main>
    </div>
  );
}
